### ISSUE TITLE
"cannot stop device without first starting device" exception during exception handling

### ISSUE THREAD

**Issue by papr** [toinsson/pyrealsense#41] opened 2017-07-05 14:48 UTC
| Required Info  |   |
|---|---|
| Camera Model | R200 | 
| Firmware Version | 1.0.71.06, 1.0.72.06 | 
| Operating System & Version | macOS Sierra 10.12.5  |
| librealsense version | 1.12.1 |
| pyrealsense version | 2.0 |
| python version | 3.6.0 |

I installed `librealsense` using `homebrew` and `pyrealsense` with `pip`. 
Afterwards I tried running the opencv example with `python3 show_cv2.py`.

Full terminal output:
https://gist.github.com/papr/f5772772b960a6487fd870569c6b1d35

**Comment by papr** [comment] 2017-07-05 15:04
Looking into the code the problem arises from [this line](https://github.com/toinsson/pyrealsense/blob/master/pyrealsense/core.py#L160) and that it does not check if the device has been opened before. Then again, this might be an issue of `librealsense`.

**Comment by mkassner** [comment] 2017-07-06 08:56
the exception seems valid. I think the real problem is:

```
ERROR:pyrealsense.utils: get_stream_ctrl_format_size(...) returned Invalid mode
```

**Comment by papr** [comment] 2017-07-06 09:32
I agree, that this is the actual problem for us, but an unhandled exception during an exception is not something one usually wants.

**Comment by toinsson** [comment] 2017-07-07 09:41
did you get the error on **first** run of `python3 show_cv2.py`, just after installing everything?
If yes, then this should be fixed - the examples must run out of the box.

I am wondering if the issue is with the camera and service not being exited properly. There are difference between platform, and closing the example on Mac might leave something running in the background.

**Comment by papr** [comment] 2017-07-07 10:37
Yes, I got this consistently. This is due to #42 . I think the example closes everything correctly.

**Comment by toinsson** [comment] 2017-07-07 13:27
ok, I'll try to reproduce this next week.

**Closed** 2020-08-17 09:39 UTC
